# Logger Configuration
logging:
  level: INFO
  file: logs/congestion_control.log
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Network Configuration
network:
  interface: eth0
  buffer_size: 65535
  raw_socket: true